apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: dev-properties
  envs:
  - dev.properties

namespace: dev

commonLabels:
  env: dev
  app: helloworld

resources:
- hw-depl.yaml
- hw-svc.yaml