---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: argocd-service
spec:
  selector:
    app: argocd
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP