apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: argocd-properties
  envs:
  - argocd.properties

namespace: dev

commonLabels:
  env: dev
  app: argocd

resources:
- argocd-depl.yaml
- argocd-svc.yaml