apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: qa-properties
  envs:
  - qa.properties

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: dev-properties
  $patch: delete

resources:
- ../../dev/helloworld

namespace: qa

commonLabels:
  env: qa
  app: helloworld

images: 
- name: tykola/hello-spring
  newTag: qa

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-world
      spec:
        template:
          spec:
            containers:
            - name: hello-world-pod
              env:
              - name: DEMO_GREETING
                value: "Hello from the environment"
              - name: DEMO_FAREWELL
                value: "Such a sweet sorrow"
              - name: ENV_PREFIX
                valueFrom:
                  configMapKeyRef:
                    name: qa-properties
                    key: env.prefix


