apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
- ../../dev/meta

patches:
patches: 
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: qa.com
    target:
      kind: Ingress
